#Utilisateurs - Format: username=password|nom|telephone
#Mon Apr 20 18:44:04 EAT 2026
test=test123|Test User|1234567890
admin=admin123|Administrateur|0000000000
user=password|Standard User|0987654321
